### PR TITLE
Add Helen Chong to member list

### PR DESCRIPTION
**Pull request by helenclx**
Hi, I would like to join a11y-webring.club. Thank you!

### CODE REVIEW

**Review by ericwbailey — APPROVED** [review]
Welcome! 🎉

**Comment by ericwbailey** [comment]
@helenclx I think you will need to submit a new PR with the same JSON file you included in this PR. Deleting your fork before I merged this PR means there is no file to integrate 😅

No worries on my end of things, I just want to make sure you're added!

**Comment by helenclx** [comment]
> @helenclx I think you will need to submit a new PR with the same JSON file you included in this PR. Deleting your fork before I merged this PR means there is no file to integrate 😅
> 
> No worries on my end of things, I just want to make sure you're added!

Oops, sorry about that! 😅 I just recreated the PR here: https://github.com/ericwbailey/a11y-webring.club/pull/184

**Comment by ericwbailey** [comment]
Not a problem at all 🙂 Merged your new PR, so you should be all set!

**Pull request closed without merging**
