### PR TITLE
Add DJ Chase.json

### PR DESCRIPTION
**Pull request by u9000-Nine**

### CODE REVIEW

**Comment by ericwbailey** [comment]
Welcome!

**Comment by ericwbailey** [comment]
I'm a little confused here. This webring is not associated with fediring.net. I am also able to use the webring links for this webring from multiple browsers at [the URL you provided](https://dj-chase.com/meta/rings-and-clubs.gmi).

**Comment by u9000-Nine** [comment]
Sorry, I meant my site isn’t on a11y-webring.club. Apologies, I’m also registering at Fediring right now which lead to the mixup.

**Comment by ericwbailey** [comment]
Ahh, gotcha. Thanks for clarifying. I think I know what happened here, and it's an oversight on my part. It looks like [the name field in the JSON](https://github.com/ericwbailey/a11y-webring.club/pull/111/files#diff-3409d7a65a366b54b13b0d5b28091d2e1908cde3e4a3169b1542c5bcc7cd65c1R3) is set to my name and I didn't catch that in review.

I can fix that on my end of things, but before I do: what name would you like me to use there?

**Comment by u9000-Nine** [comment]
Oops, sorry. "DJ Chase" please. Thank you ☺️

**Comment by ericwbailey** [comment]
I just merged https://github.com/ericwbailey/a11y-webring.club/pull/118. Hopefully this will fix things 🤞

**Comment by u9000-Nine** [comment]
I’m on the site now, but the previous and next links still act like random? Also, I appreceate you going through this with me; thank you.

**Pull request merged**
